### ISSUE TITLE
.magnifying-glass css styles not effecting the magnifying glass lens

### ISSUE THREAD

**Issue by david-j-m** [supercoww/svelte-magnifier#3]
Hi I have the following styles
` :global(.magnifying-glass) {
		/* Styles for magnifying glass */
    border-radius: 15%;
    border: 5px solid rgba(0,0,0,.5) !important; 
	}
`
This has no effect on the border which remains - square, white and solid

**Comment by ambarvm** [comment]
Hi David, this happened because the specificity of internal component styles is more than your styles.
You can increase specificity by using a [descendant combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator) or adding `!important` which is usually not recommended.

Checkout this [Svelte REPL](https://svelte.dev/repl/32748d27bbfb4cf79c19d191c038d551?version=3.49.0) for an example.

**Comment by david-j-m** [comment]
Thanks for your quick reply Ambar. Adding specificity  took care of the
issue.

[image: width=]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
